name: Deploy Landing Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/landing-pages
          # Create timestamped release
          release_dir="releases/$(date +%Y%m%d%H%M%S)"
          mkdir -p $release_dir
          git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/luminawebs/landing.git $release_dir
          
          # Install dependencies if needed
          cd $release_dir
          # npm install  # if using Node.js
          
          # Symlink to production
          ln -sfn /var/www/landing-pages/$release_dir /var/www/html/landing
          
          # Restart Nginx/Apache if needed
          sudo systemctl reload nginx